### python은 else의 3가지 용법

- 조건문
- 반복문
- 예외처리



#### 조건문

if ~else는 조건식이 False일때 else가 실행된다.

```python
if a > 3:
    print('Yes')
else:
    print('No')
    
> No


# jumsu가 80이상 '상', 80미만~60이상 '중', 60미만 '하'
jumsu = 55
if jumsu >= 80:
    print('상')
elif jumsu >= 60:
    print('중')
else:
    print('하')

> 하


# 조건식이 True일때만 수행해야 하는 경우 else는 생략할 수 있다.
a = 5
if a > 3:
    print('Yes')
    
> Yes
```



####  existance

python에서 조건은 존재론(existance)적이다.->truthy, falsy

```python
# and는 앞이 True이면 뒤에 값을 반환한다.

3 and 4 # 존재론적으로 3은 True, 4도 True -> and 연산 결과 두번째 값의 결과값이 리턴된다.

# or는 and의 반대
# 앞이 True이면 앞, 앞이 False이면 뒤의 값을 반환한다.
3 or 4
```



### 반복문

반복문에서 else는 반복문이 완벽하게 끝났을 때 실행된다.
대부분의 프로그래밍 언어는 while과 for를 지원한다.

```python
a = 10

while a>10:
    a -= 1  # a = a - 1
    print(a)
else:
    print('end')

> end
# 아래는 while문이 완벽히 돌았으므로 end가 출력된다.
```

break는 반복문을 중단시킨다.
break가 실행되면 반복문이 완벽하게 실행된 것이 아니므로 else가 실행되지 않는다.

```python
a = 10
while a>1:
    a -= 1    # a = a - 1 
    if a==5:
        break  # 중단
    print(a)
else:
    print('end')

> 9 8 7 6
```

continue는 다음 루프로 바로 넘어간다.
반복문을 중단하지는 않는다.

```python
a = 10
while a>1:
    a -= 1    # a = a - 1
    if a==5:
        continue  # 이하 코드는 실행되지 않고 다음 루프로 넘어감
    print(a)
else:
    print('end')
> 9 8 7 6 4 3 2 1 end
```



### zip

zip의 결과를 튜플로 반환한다.
zip의 iterable의 같은 인덱스의 요소들을 묶어서 반환한다.

```python
for i in zip((1,2),(3,4)):
    print(i)
> (1, 3)
(2, 4)
```



### enumerate

enumerate는 index를 생성해서 사용할 때 이용한다.
for에 넣어 사용할 수 있다.

```python
# (순서, 값)의 형태로 iterable을 바꿔준다.
for i in enumerate([1,2,3,4,5]):
    print(i)
    
> (0, 1)
(1, 2)
(2, 3)
(3, 4)
(4, 5)
```



### 예외처리문

예외처리문은 에러가 발생해도 코드를 중단하지 않고 실행한다.



예외처리문은 try ~ except~ else ~ finally로 구성된다.
try에서 실행되는 코드에 에러가 발생할 경우 except가 실행된다.
try에서 실행되는 코드가 정상적 처리가 되면 else가 실행된다.
finally는 무조건 마지막에 실행된다.

```python
# try블록이 정상적으로 실행되지 않으면 else블록은 실행되지 않는다.
# try 실행 -> except 실행 -> finally 실행
try:
    a = int(3)
    b = int('a')
except ValueError:
    print('숫자가 아닌 문자가 입력되었습니다.')
else:
    print('{}와 {}의 합:{}'.format(a,b,a+b))
finally:
    print('grogram end')
    
> 숫자가 아닌 문자가 입력되었습니다.
grogram end
```

다중 except는 에러에 해당되는거만 실행이된다

```python
try:
    # a = 1/'a'
    a = 1/0
except ZeroDivisionError:
    print('분모는 0보다 큰 수만 가능합니다.')
except TypeError as e:
    print('숫자만 가능합니다.')
    print(e)
    print()
except:
    print('except')
else:
    print('end')
finally:
    print('program end')
> 분모는 0보다 큰 수만 가능합니다.
program end
```

